Increment 17
romm80/shortener pull request #20
Opened 2022-05-31 12:29 UTC by romm80

2022-05-31 12:33 UTC, romm80 commented
Не совсем понял что можно оптимизировать, бизнес логики как таковой нет, но что то вроде получилось судя по цифрам))

2022-06-05 22:59 UTC, Barugoo commented on internal/app/handlers/doc.go
> +// Модуль handlers предназначен для маршрутизации и обработки http запросов
Давай комменты все на англицком писать

2022-06-05 23:00 UTC, Barugoo requested changes
За сваггер - однозначно лайк, не вижу бенчмарков. Как идея можно сделать две реализации хранилки урлов - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях.

2022-06-10 07:35 UTC, Barugoo approved these changes
Отлично!

2022-06-10 08:12 UTC, merged